name: Deploy to VPS

on:
  push:
    branches:
      - master  # Trigger deployment on push to main branch, adjust if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to VPS
      run: scp -o StrictHostKeyChecking=no -r . jaseem@203.161.61.93:/var/www/gigantic
