name: Deploy to VPS

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 203.161.61.93 >> ~/.ssh/known_hosts

    - name: Copy files to VPS
      run: scp -o StrictHostKeyChecking=no -r . jaseem@203.161.61.93:/var/www/gigantic
